---
name: Renovate config

on:
  pull_request:
    branches:
      - main

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.272.5@sha256:b908d84857c6efee646b46c674ac081f57e54828b164f91f53e087d1d71e1d62
      # github hosted runners are running as `1001:127` (ubuntu:docker)
      options: -u 1001:0 --group-add 1000 --group-add 12021 --group-add 127
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate global configuration
        run: renovate-config-validator .github/renovate-global.json
