---
name: Renovate config

on:
  pull_request:
    branches:
      - main

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.275.0@sha256:f0902eb911e2aa39e51ec87f0a0b4ecf7a97ced493a3252cf0fab0fdc9d6ec69
      # github hosted runners are running as `1001:127` (ubuntu:docker)
      options: -u 1001:0 --group-add 1000 --group-add 12021 --group-add 127
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate global configuration
        run: renovate-config-validator .github/renovate-global.json
