---
name: Renovate

concurrency:
  group: ${{ github.workflow }}

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create app token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Run self-hosted Renovate
        env:
          LOG_FILE: /tmp/renovate-log.jsonl
          LOG_FILE_FORMAT: json
          LOG_FILE_LEVEL: debug
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: .github/renovate-global.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          env-regex: "^(?:RENOVATE_\\w+|LOG_\\w+|GITHUB_COM_TOKEN|NODE_OPTIONS|NO_COLOR|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy)$"
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 43.272.6@sha256:b640a73476ded79cc9bb90fd69dff81876220f1c8a5c454fb7ddf23cd8d1e627
          token: ${{ steps.app-token.outputs.token }}
      - name: Upload Renovate logs to Backblaze bucket
        env:
          LOG_FILE: /tmp/renovate-log.jsonl
        if: ${{ !cancelled() }}
        run: |
          [[ -e $LOG_FILE ]] || exit 0

          AUTHZ=$(curl -sf -u "${{ secrets.BACKBLAZE_KEY_ID }}:${{secrets.BACKBLAZE_APPLICATION_KEY }}" https://api.backblazeb2.com/b2api/v4/b2_authorize_account)
          AUTHZ_TOKEN=$(echo $AUTHZ | jq -r .authorizationToken)
          echo "::add-mask::$AUTHZ_TOKEN"
          API_URL=$(echo $AUTHZ | jq -r .apiInfo.storageApi.apiUrl)
          echo "::add-mask::$API_URL"

          UPLOAD=$(curl -sf -H "Authorization: $AUTHZ_TOKEN" \
          -d '{"bucketId": "${{ secrets.BACKBLAZE_BUCKET_ID }}"}' \
          $API_URL/b2api/v4/b2_get_upload_url)
          UPLOAD_URL=$(echo $UPLOAD | jq -r .uploadUrl)
          echo "::add-mask::$UPLOAD_URL"
          UPLOAD_AUTHZ_TOKEN=$(echo $UPLOAD | jq -r .authorizationToken)
          echo "::add-mask::$UPLOAD_AUTHZ_TOKEN"

          curl -sf -H "Authorization: $UPLOAD_AUTHZ_TOKEN" \
          -H "X-Bz-File-Name: logs%2Frenovate-$(TZ=Europe/Brussels date +%Y%m%d%H%M).jsonl" \
          -H "Content-Type: application/jsonl" \
          -H "Content-Length: $(stat --format %s $LOG_FILE)" \
          -H "X-Bz-Content-Sha1: $(sha1sum $LOG_FILE | cut -f1 -d ' ')" \
          --data-binary "@$LOG_FILE" \
          $UPLOAD_URL > /dev/null
