---
name: Renovate config

on:
  pull_request:
    branches:
      - main

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.251.0@sha256:c42ddcaa72e5364809557a07a551917eac835c6e8c0818e32b2964f71383114e
      # github hosted runners are running as `1001:127` (ubuntu:docker)
      options: -u 1001:0 --group-add 1000 --group-add 12021 --group-add 127
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Validate global configuration
        run: renovate-config-validator .github/renovate-global.json
